Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2020-12, with the labels that each got.

#559 add indexing to pwl vars
  src/devices_models/devices/common/cost_functions.jl
Labels: bug

#564 bump time series
  Project.toml
Labels: Upstream

#565 Adding Cache type for storage initial condition
  src/core/update_initial_conditions.jl
Labels: bug

#566 Cost Function re-factor
  src/core/psi_container.jl
  src/devices_models/devices/common/cost_functions.jl
  test/test_data/data_14bus_pu.jl
  test/test_data/data_5bus_pu.jl
  test/test_utils/get_test_data.jl
Labels: bug

#567 sim store integration
  Project.toml
  src/PowerSimulations.jl
  src/core/definitions.jl
  src/core/feedforward.jl
  src/core/hdf_simulation_store.jl
  src/core/operations_problem.jl
  src/core/operations_problem_results.jl
  src/core/optimizer_stats.jl
  src/core/psi_container.jl
  src/core/psi_settings.jl
  src/core/result_cache.jl
  src/core/simulation.jl
  src/core/simulation_results.jl
  src/core/simulation_sequence.jl
  src/core/simulation_stages.jl
  src/core/simulation_store.jl
  src/printing.jl
  src/utils.jl
  test/Project.toml
  test/runtests.jl
  test/test_operations_solve.jl
  test/test_simulation_build.jl
  test/test_simulation_execute.jl
  test/test_simulation_results.jl
  test/test_simulation_sequence.jl
  test/test_simulation_store.jl
Labels: enhancement

#560 Change method dispatch
  src/PowerSimulations.jl
  src/core/aux_structs.jl
  src/core/definitions.jl
  src/core/feedforward.jl
  src/core/initial_condition_types.jl
  src/core/initial_conditions.jl
  src/core/models.jl
  src/core/operations_problem.jl
  src/core/operations_problem_results.jl
  src/core/psi_container.jl
  src/core/recorder_events.jl
  src/core/simulation.jl
  src/core/simulation_sequence.jl
  src/core/simulation_stages.jl
  src/core/update_initial_conditions.jl
  src/core/variables.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/DC_branches.jl
  src/devices_models/devices/common.jl
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/common/device_range_constraints.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/range_constraint.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/interfaces.jl
  src/devices_models/devices/regulation_device.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/storage.jl
  src/devices_models/devices/thermal_generation.jl
  src/network_models/network_constructor.jl
  src/network_models/networks.jl
  src/network_models/powermodels_interface.jl
  src/network_models/ptdf_model.jl
  src/printing.jl
  src/services_models/agc.jl
  src/services_models/group_reserve.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  src/services_models/services_model.jl
  src/utils.jl
  test/runtests.jl
Labels: enhancement

#573 Simulation store merge
  .github/workflows/master-tests.yml
  Project.toml
  src/PowerSimulations.jl
  src/core/aux_structs.jl
  src/core/cache_utils.jl
  src/core/definitions.jl
  src/core/feedforward.jl
  src/core/initial_condition_types.jl
  src/core/initial_conditions.jl
  src/core/models.jl
  src/core/operations_problem.jl
  src/core/operations_problem_results.jl
  src/core/psi_container.jl
  src/core/recorder_events.jl
  src/core/simulation.jl
  src/core/simulation_sequence.jl
  src/core/simulation_stages.jl
  src/core/update_initial_conditions.jl
  src/core/variables.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/DC_branches.jl
  src/devices_models/devices/common.jl
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/common/device_range_constraints.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/nodal_expression.jl
  src/devices_models/devices/common/range_constraint.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/interfaces.jl
  src/devices_models/devices/regulation_device.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/storage.jl
  src/devices_models/devices/thermal_generation.jl
  src/network_models/network_constructor.jl
  src/network_models/networks.jl
  src/network_models/powermodels_interface.jl
  src/network_models/ptdf_model.jl
  src/printing.jl
  src/services_models/agc.jl
  src/services_models/group_reserve.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  src/services_models/services_model.jl
  src/utils.jl
  test/test_data/data_14bus_pu.jl
  test/test_data/data_5bus_pu.jl
  test/test_operations_solve.jl
  test/test_simulation_execute.jl
  test/test_simulation_results.jl
  test/test_utils/get_test_data.jl
Labels: URGENT, enhancement
