Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2020-08, with the labels that each got.

#494 Empty contributing devices case
  src/core/simulation.jl
  src/core/update_initial_conditions.jl
  src/devices_models/device_constructors/common/constructor_validations.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/services_models/agc.jl
  src/services_models/services_constructor.jl
Labels: bug

#500 bump psy
  src/core/psi_container.jl
  test/test_data/data_14bus_pu.jl
  test/test_data/data_5bus_pu.jl
  test/test_device_thermal_generation_constructors.jl
  test/test_utils/get_test_data.jl
Labels: Upstream

#501 fix incorrect recorder assignment
  src/core/recorder_events.jl
Labels: bug

#502 resolving issues with pwl cost creation in ThermalDispatchNoMin formu…
  src/devices_models/devices/thermal_generation.jl
  test/test_operations_constructor.jl
  test/test_utils/get_test_data.jl
Labels: bug

#487 Add StaticGroupReserve Handling
  src/PowerSimulations.jl
  src/devices_models/device_constructors/common/constructor_validations.jl
  src/services_models/GroupReserve.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  test/test_services_constructor.jl
Labels: enhancement

#504 Incorrect order of arguments
  src/devices_models/devices/storage.jl
Labels: bug

#510 remove generators for names and axis
  src/core/feedforward.jl
  src/core/simulation_stages.jl
  src/devices_models/devices/DC_branches.jl
  src/devices_models/devices/common/add_parameters.jl
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/common/duration_constraints.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/range_constraint.jl
  src/devices_models/devices/common/rateofchange_constraints.jl
  src/devices_models/devices/common/timeseries_constraint.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/regulation_device.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/thermal_generation.jl
  src/network_models/powermodels_interface.jl
  src/services_models/agc.jl
Labels: enhancement
