Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2020-10, with the labels that each got.

#516 refactor cost functions
  src/core/definitions.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/thermal_generation.jl
  src/services_models/reserves.jl
Labels: URGENT, enhancement

#528 ph merge
  src/PowerSimulations.jl
  src/core/constraints.jl
  src/core/initial_condition_types.jl
  src/core/simulation.jl
  src/core/simulation_results.jl
  src/core/simulation_sequence.jl
  src/core/update_initial_conditions.jl
  src/core/variables.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/storage.jl
  test/test_data/data_5bus_pu.jl
  test/test_device_hydro_generation_constructors.jl
  test/test_utils/get_test_data.jl
Labels: UPGRADE

#536 Add test for StaticReserve as RangeReserve
  src/services_models/reserves.jl
  test/test_services_constructor.jl
Labels: enhancement

#537 comment out PG docs
  docs/Project.toml
  docs/make.jl
  docs/src/get_test_data.jl
  docs/src/howto/generic_report_template.jmd
Labels: documentation
