Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2021-06, with the labels that each got.

#694 Bug Fix in MarketBidCost for Service
  src/devices_models/devices/common/cost_functions.jl
  test/test_device_thermal_generation_constructors.jl
Labels: code bug

#698 Bug Fix in ThermalNoMin cost function for PWL data
  src/devices_models/devices/thermal_generation.jl
Labels: code bug

#699 performance branch 7
  src/core/aux_structs.jl
  src/core/cache.jl
  src/core/simulation_sequence.jl
  src/printing.jl
  test/runtests.jl
  test/test_simulation_sequence.jl
  test/test_utils/mock_operation_models.jl
Labels: enhancement

#700 check execution in initical condition
  src/core/simulation.jl
Labels: code bug

#703 parameter container refactor part1
  src/PowerSimulations.jl
  src/core/abstract_types.jl
  src/core/aux_structs.jl
  src/core/constraints.jl
  src/core/feedforward.jl
  src/core/optimization_container.jl
  src/core/parameters.jl
  src/core/recorder_events.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/common/add_parameters.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/common/device_range_constraints.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/energy_management_constraints.jl
  src/devices_models/devices/common/get_time_series.jl
  src/devices_models/devices/common/nodal_expression.jl
  src/devices_models/devices/common/timeseries_constraint.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/regulation_device.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/storage.jl
  src/devices_models/devices/thermal_generation.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  test/Project.toml
  test/runtests.jl
  test/test_device_thermal_generation_constructors.jl
Labels: new release

#706 Fix services and storage modeling bugs
  src/core/simulation_sequence.jl
  src/devices_models/device_constructors/common/constructor_validations.jl
  src/devices_models/devices/storage.jl
  src/services_models/services_constructor.jl
Labels: code bug
