Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2021-01, with the labels that each got.

#585 add progress meter
  Project.toml
  src/PowerSimulations.jl
  src/core/psi_container.jl
  src/core/psi_settings.jl
  src/core/simulation.jl
  src/core/simulation_stages.jl
Labels: enhancement

#587 Minor bug Fixes
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/thermal_generation.jl
Labels: bug

#589 Simulation store
  Project.toml
  src/PowerSimulations.jl
  src/core/cache_utils.jl
  src/core/definitions.jl
  src/core/feedforward.jl
  src/core/hdf_simulation_store.jl
  src/core/operations_problem.jl
  src/core/operations_problem_results.jl
  src/core/optimizer_stats.jl
  src/core/param_result_cache.jl
  src/core/psi_container.jl
  src/core/psi_settings.jl
  src/core/result_cache.jl
  src/core/simulation.jl
  src/core/simulation_results.jl
  src/core/simulation_results_export.jl
  src/core/simulation_sequence.jl
  src/core/simulation_stages.jl
  src/core/simulation_store.jl
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/common/pm_translator.jl
  src/devices_models/devices/thermal_generation.jl
  src/printing.jl
  src/services_models/reserves.jl
  src/utils.jl
  test/Project.toml
  test/runtests.jl
  test/test_base_structs.jl
  test/test_data/data_14bus_pu.jl
  test/test_data/data_5bus_pu.jl
  test/test_data/results_export.json
  test/test_device_branch_constructors.jl
  test/test_device_hydro_generation_constructors.jl
  test/test_device_load_constructors.jl
  test/test_device_renewable_generation_constructors.jl
  test/test_device_storage_constructors.jl
  test/test_device_thermal_generation_constructors.jl
  test/test_network_constructors.jl
  test/test_operations_constructor.jl
  test/test_operations_modifications.jl
  test/test_operations_solve.jl
  test/test_services_constructor.jl
  test/test_simulation_build.jl
  test/test_simulation_execute.jl
  test/test_simulation_results.jl
  test/test_simulation_results_export.jl
  test/test_simulation_sequence.jl
  test/test_simulation_store.jl
  test/test_utils/get_test_data.jl
Labels: UPGRADE, URGENT

#583 Updating Thermal Formulations
  src/PowerSimulations.jl
  src/core/variables.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/thermal_generation.jl
  test/test_device_thermal_generation_constructors.jl
  test/test_simulation_build.jl
  test/test_utils/operations_problem_templates.jl
Labels: enhancement

#594 Bug fix in Parameter value
  src/core/simulation_stages.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/hydro_generation.jl
Labels: bug

#596 Bug fix in hydro target constraint
  src/devices_models/devices/common/energy_balance_constraint.jl
Labels: bug

#598 Fixing multiplier array NaN issue
  src/core/feedforward.jl
  src/services_models/reserves.jl
Labels: bug
