Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2021-03, with the labels that each got.

#617 Jd/network modeling patch
  Project.toml
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/network_models/copperplate_model.jl
Labels: enhancement

#616 multistart patches
  Project.toml
  docs/make.jl
  src/PowerSimulations.jl
  src/core/cache_utils.jl
  src/core/feedforward.jl
  src/core/hdf_simulation_store.jl
  src/core/operations_problem.jl
  src/core/operations_problem_results.jl
  src/core/optimization_container.jl
  src/core/optimizer_stats.jl
  src/core/problem_results_export.jl
  src/core/result_cache.jl
  src/core/simulation.jl
  src/core/simulation_results.jl
  src/core/simulation_results_export.jl
  src/core/simulation_store.jl
  src/core/update_initial_conditions.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/common/cost_functions.jl
  src/operations_problem_templates.jl
  src/printing.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  src/utils.jl
  test/runtests.jl
  test/test_data/results_export.json
  test/test_device_branch_constructors.jl
  test/test_operations_problem.jl
  test/test_services_constructor.jl
  test/test_simulation_results.jl
  test/test_simulation_results_export.jl
  test/test_utils/model_checks.jl
  test/test_utils/operations_problem_templates.jl
Labels: bug

#624 fix incorrect implementations
  src/core/service_models.jl
  src/core/simulation.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/DC_branches.jl
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/interfaces.jl
  src/devices_models/devices/regulation_device.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/storage.jl
  src/devices_models/devices/thermal_generation.jl
  src/network_models/powermodels_interface.jl
  src/services_models/agc.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  test/test_device_thermal_generation_constructors.jl
Labels: URGENT

#628 fix rh simulation
  src/PowerSimulations.jl
  src/core/feedforward.jl
  src/core/feedforward_chronologies.jl
  src/core/operations_problem.jl
  src/core/optimization_container.jl
  src/core/simulation.jl
Labels: bug

#630 pj deprecation
  src/core/feedforward.jl
  src/core/update_initial_conditions.jl
  src/devices_models/devices/common/add_parameters.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/timeseries_constraint.jl
  src/devices_models/devices/hydro_generation.jl
  src/services_models/reserves.jl
  src/utils.jl
Labels: Upstream

#634 fix hvdc implementation
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/devices/DC_branches.jl
  test/test_device_branch_constructors.jl
  test/test_utils/operations_problem_templates.jl
Labels: enhancement

#641 Hydro Refactor
  src/PowerSimulations.jl
  src/core/constraints.jl
  src/core/variables.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/energy_management_constraints.jl
  src/devices_models/devices/common_models.jl
  src/devices_models/devices/hydro_generation.jl
  test/runtests.jl
  test/test_device_hydro_generation_constructors.jl
  test/test_simulation_results.jl
Labels: enhancement

#642 011 patch2
  src/core/operations_problem.jl
  src/devices_models/devices/common/rating_constraints.jl
  src/printing.jl
Labels: enhancement

#645 resolving bug in PTDF with lines and transformers
  src/core/constraints.jl
  src/core/optimization_container.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/DC_branches.jl
  src/devices_models/devices/hydro_generation.jl
  src/network_models/powermodels_interface.jl
  test/test_device_branch_constructors.jl
  test/test_network_constructors.jl
  test/test_operations_problem.jl
  test/test_utils/model_checks.jl
Labels: bug

#643 Prefetch sequential reads of time series data
  src/core/operations_problem.jl
  src/core/param_result_cache.jl
  src/core/settings.jl
  src/core/simulation.jl
  test/test_simulation_results.jl
Labels: enhancement

#659 correct sign in reserve ramps
  src/devices_models/devices/common/rateofchange_constraints.jl
Labels: modeling bug
