Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2021-05, with the labels that each got.

#675 Adding Storage formulation with reserves
  src/PowerSimulations.jl
  src/core/constraints.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/common/range_constraint.jl
  src/devices_models/devices/storage.jl
  src/services_models/reserves.jl
  test/test_device_storage_constructors.jl
Labels: enhancement

#682 bug fix in PTDF LMPs calculation
  test/test_operations_problem.jl
  test/test_utils/model_checks.jl
Labels: code bug

#683 add auxiliary vars - part 1
  .github/workflows/format-check.yml
  src/PowerSimulations.jl
  src/core/aux_structs.jl
  src/core/auxiliary_variables.jl
  src/core/initial_condition.jl
  src/core/initial_condition_types.jl
  src/core/initial_conditions.jl
  src/core/operations_problem.jl
  src/core/optimization_container.jl
  src/core/problem_results.jl
  src/core/recorder_events.jl
  src/core/simulation.jl
  src/core/update_initial_conditions.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/common/add_auxiliary_variable.jl
  src/devices_models/devices/common/duration_constraints.jl
  src/devices_models/devices/common/range_constraint.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/storage.jl
  src/devices_models/devices/thermal_generation.jl
  src/network_models/powermodels_interface.jl
  src/utils.jl
  test/test_device_thermal_generation_constructors.jl
  test/test_simulation_results.jl
  test/test_utils/model_checks.jl
  test/test_utils/solver_definitions.jl
Labels: enhancement

#689 performance patch1
  .gitignore
  src/PowerSimulations.jl
  src/core/initial_conditions.jl
  src/core/operations_problem.jl
  src/core/optimization_container.jl
  src/core/settings.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/storage.jl
  src/services_models/reserves.jl
  test/test_device_storage_constructors.jl
Labels: URGENT, enhancement

#691 performance patch3
  src/core/optimization_container.jl
  src/devices_models/devices/AC_branches.jl
Labels: enhancement
