Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2021-04, with the labels that each got.

#663 addressing #654
  src/devices_models/devices/thermal_generation.jl
  test/runtests.jl
Labels: code bug

#662 Add option to store simulation results in memory
  src/PowerSimulations.jl
  src/core/hdf_simulation_store.jl
  src/core/in_memory_simulation_store.jl
  src/core/operations_problem.jl
  src/core/optimization_container.jl
  src/core/param_result_cache.jl
  src/core/problem_results.jl
  src/core/simulation.jl
  src/core/simulation_results.jl
  src/core/simulation_store.jl
  src/utils.jl
  test/test_simulation_results.jl
  test/test_simulation_store.jl
  test/test_utils.jl
  test/test_utils/model_checks.jl
Labels: enhancement

#665 fixing bug in duration ic from indexing with float
  src/core/simulation.jl
  src/devices_models/devices/common/duration_constraints.jl
  src/devices_models/devices/thermal_generation.jl
  src/printing.jl
  test/test_simulation_results.jl
  test/test_simulation_sequence.jl
Labels: code bug

#668 fixing increment calculation
  src/core/simulation.jl
Labels: code bug

#669 Cb/exec order
  src/core/simulation.jl
  test/test_simulation_build.jl
Labels: code bug

#646 DNMY: Storage Refactor
  docs/src/man/end_of_period_energy_target.md
  docs/src/man/storage_energy_target.md
  src/PowerSimulations.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/devices/common/cost_functions.jl
  src/devices_models/devices/common/energy_balance_constraint.jl
  src/devices_models/devices/common/energy_management_constraints.jl
  src/devices_models/devices/common_models.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/storage.jl
  test/runtests.jl
  test/test_device_hydro_generation_constructors.jl
  test/test_device_storage_constructors.jl
  test/test_simulation_execute.jl
  test/test_simulation_results.jl
Labels: enhancement

#671 Bug fix in Multi-start start type constraint
  src/devices_models/devices/thermal_generation.jl
Labels: modeling bug

#672 Adding Ramp Reserve
  src/PowerSimulations.jl
  src/devices_models/devices/common/constraints_structs.jl
  src/devices_models/devices/common/rateofchange_constraints.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  test/test_services_constructor.jl
Labels: modeling bug
