Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2023-09, with the labels that each got.

#1001 Jdrh/fix reserves
  Project.toml
  src/PowerSimulations.jl
  src/core/constraints.jl
  src/core/variables.jl
  src/devices_models/devices/common/add_to_expression.jl
  src/devices_models/devices/common/objective_functions.jl
  src/devices_models/devices/regulation_device.jl
  src/feedforward/feedforward_arguments.jl
  src/feedforward/feedforward_constraints.jl
  src/feedforward/feedforwards.jl
  src/operation/initial_conditions_update_in_memory_store.jl
  src/parameters/add_parameters.jl
  src/parameters/update_parameters.jl
  src/services_models/agc.jl
  src/services_models/group_reserve.jl
  src/services_models/reserve_group.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  src/utils/jump_utils.jl
  test/Project.toml
  test/test_basic_model_structs.jl
  test/test_services_constructor.jl
Labels: enhancement

#999 Removing remainder hydro code from PowerSimulations
  src/PowerSimulations.jl
  src/core/formulations.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/devices/hydro_generation.jl
  test/test_device_hydro_generation_constructors.jl
Labels: new release

#1003 Jd/hvdc model
  Project.toml
  docs/src/formulation_library/Branch.md
  src/PowerSimulations.jl
  src/core/definitions.jl
  src/core/formulations.jl
  src/core/network_model.jl
  src/core/optimization_container.jl
  src/core/variables.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/device_constructors/hvdcsystems_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/HVDCsystems.jl
  src/devices_models/devices/TwoTerminalDC_branches.jl
  src/devices_models/devices/common/add_constraint_dual.jl
  src/devices_models/devices/common/add_to_expression.jl
  src/devices_models/devices/common/add_variable.jl
  src/feedforward/feedforward_arguments.jl
  src/feedforward/feedforwards.jl
  src/network_models/area_balance_model.jl
  src/network_models/hvdc_networks.jl
  src/network_models/network_constructor.jl
  src/network_models/network_slack_variables.jl
  src/network_models/pm_translator.jl
  src/network_models/powermodels_interface.jl
  src/operation/operation_model_interface.jl
  src/operation/operation_problem_templates.jl
  src/parameters/update_parameters.jl
  src/services_models/reserves.jl
  src/utils/powersystems_utils.jl
  test/Project.toml
  test/test_device_branch_constructors.jl
  test/test_device_hvdc.jl
  test/test_model_decision.jl
  test/test_network_constructors.jl
  test/test_utils/mock_operation_models.jl
  test/test_utils/operations_problem_templates.jl
Labels: new release, breaking

#1010 Jd/hvdc losses bugfix
  src/core/optimization_container.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/TwoTerminalDC_branches.jl
  src/devices_models/devices/common/add_to_expression.jl
Labels: code bug
