Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2023-03, with the labels that each got.

#936 Jd/services ff
  src/PowerSimulations.jl
  src/core/optimization_container.jl
  src/core/service_model.jl
  src/feedforward/feedforward_arguments.jl
  src/feedforward/feedforward_constraints.jl
  src/feedforward/feedforwards.jl
  src/operation/decision_model.jl
  src/operation/emulation_model.jl
  src/operation/problem_results.jl
  src/operation/problem_template.jl
  src/parameters/add_parameters.jl
  src/parameters/update_parameters.jl
  src/services_models/reserves.jl
  src/services_models/services_constructor.jl
  src/simulation/simulation_sequence.jl
  src/utils/printing.jl
  test/test_utils/mock_operation_models.jl
Labels: code bug

#947 Fix check_conflict_status on undefined constraints
  src/utils/jump_utils.jl
Labels: code bug

#950 Thermal OnVariable updates
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/common/objective_functions.jl
  src/devices_models/devices/interfaces.jl
  src/devices_models/devices/thermal_generation.jl
  test/test_device_thermal_generation_constructors.jl
Labels: modeling bug

#949 Jd/multi area coopperplate
  Project.toml
  src/core/device_model.jl
  src/core/network_model.jl
  src/core/optimization_container.jl
  src/core/parameters.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/device_constructors/hydrogeneration_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/regulationdevice_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/storage_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/AC_branches.jl
  src/devices_models/devices/DC_branches.jl
  src/devices_models/devices/common/add_constraint_dual.jl
  src/devices_models/devices/common/add_to_expression.jl
  src/devices_models/devices/common/add_variable.jl
  src/devices_models/devices/electric_loads.jl
  src/devices_models/devices/hydro_generation.jl
  src/devices_models/devices/regulation_device.jl
  src/devices_models/devices/renewable_generation.jl
  src/devices_models/devices/storage.jl
  src/devices_models/devices/thermal_generation.jl
  src/initial_conditions/initialization.jl
  src/network_models/copperplate_model.jl
  src/network_models/network_constructor.jl
  src/network_models/network_slack_variables.jl
  src/operation/decision_model.jl
  src/operation/emulation_model.jl
  src/operation/operation_model_interface.jl
  src/operation/problem_template.jl
  src/parameters/add_parameters.jl
  test/runtests.jl
  test/test_device_branch_constructors.jl
  test/test_initialization_problem.jl
  test/test_model_decision.jl
  test/test_network_constructors.jl
  test/test_utils/mock_operation_models.jl
Labels: enhancement, new release
