Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2024-03, with the labels that each got.

#1073 Fix caching behaviors: #1070, #1072, #1074
  README.md
  src/simulation/decision_model_simulation_results.jl
  src/simulation/emulation_model_simulation_results.jl
  src/simulation/simulation_problem_results.jl
  test/test_simulation_results.jl
Labels: code bug, performance

#1079 Further results cache optimizations to support PowerAnalytics
  src/simulation/decision_model_simulation_results.jl
  test/test_simulation_results.jl
Labels: performance

#1086 fix optimizer stats backwards compatibility
  src/core/optimizer_stats.jl
  test/test_utils.jl
Labels: code bug

#1092 build in parallel test
  docs/src/formulation_library/General.md
  docs/src/formulation_library/Load.md
  docs/src/formulation_library/RenewableGen.md
  src/PowerSimulations.jl
  src/core/constraints.jl
  src/core/device_model.jl
  src/core/event_keys.jl
  src/core/initial_conditions.jl
  src/core/network_model.jl
  src/core/optimization_container.jl
  src/core/parameters.jl
  src/core/service_model.jl
  src/devices_models/device_constructors/branch_constructor.jl
  src/devices_models/device_constructors/constructor_validations.jl
  src/devices_models/device_constructors/hvdcsystems_constructor.jl
  src/devices_models/device_constructors/load_constructor.jl
  src/devices_models/device_constructors/renewablegeneration_constructor.jl
  src/devices_models/device_constructors/thermalgeneration_constructor.jl
  src/devices_models/devices/common/add_constraint_dual.jl
  src/devices_models/devices/common/objective_functions.jl
  src/devices_models/devices/thermal_generation.jl
  src/initial_conditions/initialization.jl
  src/network_models/network_constructor.jl
  src/network_models/network_slack_variables.jl
  src/network_models/pm_translator.jl
  src/network_models/powermodels_interface.jl
  src/operation/decision_model.jl
  src/operation/decision_model_store.jl
  src/operation/emulation_model.jl
  src/operation/problem_template.jl
  src/parameters/update_parameters.jl
  src/simulation/decision_model_simulation_results.jl
  src/simulation/emulation_model_simulation_results.jl
  src/simulation/hdf_simulation_store.jl
  src/simulation/in_memory_simulation_store.jl
  src/simulation/simulation.jl
  src/simulation/simulation_problem_results.jl
  src/simulation/simulation_results.jl
  src/simulation/simulation_sequence.jl
  src/utils/powersystems_utils.jl
  test/Project.toml
  test/includes.jl
  test/performance/performance_test.jl
  test/runtests.jl
  test/test_ic_reconciliation.jl
  test/test_network_constructors.jl
  test/test_simulation_results.jl
  test/test_utils/mock_operation_models.jl
Labels: enhancement

#1096 add fix to service bid
  src/devices_models/devices/common/objective_functions.jl
Labels: code bug
