Repository NREL-Sienna/PowerSimulations.jl, pull requests merged in 2024-10, with the labels that each got.

#1159 Fix Unbounded HVDC model for Copperplate
  src/devices_models/device_constructors/branch_constructor.jl
Labels: code bug

#1166 Update README with docs link
  README.md
Labels: documentation

#1169 Use cached time series UUID
  src/parameters/update_container_parameter_values.jl
Labels: performance
